package java.szmq;
import org.bridj.BridJ;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
import org.bridj.cpp.CPPRuntime;
/**
 * Wrapper for library <b>szmq</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("szmq") 
@Runtime(CPPRuntime.class) 
public class SzmqLibrary {
	static {
		BridJ.register();
	}
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_PAIR = (int)0;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_PUB = (int)1;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_SUB = (int)2;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_REQ = (int)3;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_REP = (int)4;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_DEALER = (int)5;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_ROUTER = (int)6;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_PULL = (int)7;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_PUSH = (int)8;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_XPUB = (int)9;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_XSUB = (int)10;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_STREAM = (int)11;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_AFFINITY = (int)4;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_ROUTING_ID = (int)5;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_SUBSCRIBE = (int)6;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_UNSUBSCRIBE = (int)7;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_RATE = (int)8;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_RECOVERY_IVL = (int)9;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_SNDBUF = (int)11;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_RCVBUF = (int)12;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_RCVMORE = (int)13;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_FD = (int)14;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_EVENTS = (int)15;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_TYPE = (int)16;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_LINGER = (int)17;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_RECONNECT_IVL = (int)18;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_BACKLOG = (int)19;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_RECONNECT_IVL_MAX = (int)21;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_MAXMSGSIZE = (int)22;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_SNDHWM = (int)23;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_RCVHWM = (int)24;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_MULTICAST_HOPS = (int)25;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_RCVTIMEO = (int)27;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_SNDTIMEO = (int)28;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_LAST_ENDPOINT = (int)32;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_ROUTER_MANDATORY = (int)33;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_TCP_KEEPALIVE = (int)34;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_TCP_KEEPALIVE_CNT = (int)35;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_TCP_KEEPALIVE_IDLE = (int)36;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_TCP_KEEPALIVE_INTVL = (int)37;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_IMMEDIATE = (int)39;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_XPUB_VERBOSE = (int)40;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_ROUTER_RAW = (int)41;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_IPV6 = (int)42;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_MECHANISM = (int)43;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_PLAIN_SERVER = (int)44;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_PLAIN_USERNAME = (int)45;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_PLAIN_PASSWORD = (int)46;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_CURVE_SERVER = (int)47;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_CURVE_PUBLICKEY = (int)48;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_CURVE_SECRETKEY = (int)49;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_CURVE_SERVERKEY = (int)50;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_PROBE_ROUTER = (int)51;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_REQ_CORRELATE = (int)52;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_REQ_RELAXED = (int)53;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_CONFLATE = (int)54;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_ZAP_DOMAIN = (int)55;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_ROUTER_HANDOVER = (int)56;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_TOS = (int)57;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_CONNECT_ROUTING_ID = (int)61;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_GSSAPI_SERVER = (int)62;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_GSSAPI_PRINCIPAL = (int)63;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_GSSAPI_SERVICE_PRINCIPAL = (int)64;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_GSSAPI_PLAINTEXT = (int)65;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_HANDSHAKE_IVL = (int)66;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_SOCKS_PROXY = (int)68;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_XPUB_NODROP = (int)69;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_BLOCKY = (int)70;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_XPUB_MANUAL = (int)71;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_XPUB_WELCOME_MSG = (int)72;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_STREAM_NOTIFY = (int)73;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_INVERT_MATCHING = (int)74;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_HEARTBEAT_IVL = (int)75;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_HEARTBEAT_TTL = (int)76;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_HEARTBEAT_TIMEOUT = (int)77;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_XPUB_VERBOSER = (int)78;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_CONNECT_TIMEOUT = (int)79;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_TCP_MAXRT = (int)80;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_THREAD_SAFE = (int)81;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_MULTICAST_MAXTPDU = (int)84;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_VMCI_BUFFER_SIZE = (int)85;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_VMCI_BUFFER_MIN_SIZE = (int)86;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_VMCI_BUFFER_MAX_SIZE = (int)87;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_VMCI_CONNECT_TIMEOUT = (int)88;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_USE_FD = (int)89;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_GSSAPI_PRINCIPAL_NAMETYPE = (int)90;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_GSSAPI_SERVICE_PRINCIPAL_NAMETYPE = (int)91;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_BINDTODEVICE = (int)92;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_MORE = (int)1;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_SHARED = (int)3;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_DONTWAIT = (int)1;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final int ZMQ_SNDMORE = (int)2;
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final String SERVER_BIND_ENDPOINT = (String)"tcp://*:9000";
	/** <i>native declaration : src/main/native/szmq/include/Socket.hpp</i> */
	public static final String CLIENT_CONNECT_ENDPOINT = (String)"tcp://127.0.0.1:9000";
}
